<?php

/**
 * @file
 * Main file of Hello World module.
 */

/**
 * Implements hook_block_info().
 */
function myform_block_info() {
  $blocks = array();

  $blocks['myform'] = array(
    'info' => t('My form for test send mail'),
  );

  return $blocks;
}

function myform_menu($delta = '') {
    $item = array();
    $item['myform'] = array(
        'title'=>t('Test send mail'),
        'description'=>t('Test send mail'),
        'page callback'=>'myform_callback',
        'access arguments'=>array('access content'),
        'type'=>MENU_CALLBACK
    );
    return $item;
}

function myform_callback(){
    return drupal_get_form('myform_my_form');
}

/**
* This function is called the "form builder". It builds the form.
* Notice, it takes one argument, the $form_state
*/
function myform_my_form($form_state) {
//  Code sample tu che
//  $form['name'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Name'),
//  );
//  $form['email'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Email'),
//  );
//  $form['content'] = array(
//    '#type' => 'textarea',
//    '#title' => t('Content'),
//  );



//    Code sample #4
//    $form['name'] = array(
//    '#type' => 'fieldset',
//    '#title' => t('Name'),
//    '#collapsible' => TRUE, // Added
//    '#collapsed' => FALSE,  // Added
//  );
//  // To make these fields required
//  $form['name']['first'] = array(
//    '#type' => 'textfield',
//    '#title' => t('First name'),
//    '#required' => TRUE, // Added
//  );
//  $form['name']['last'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Last name'),
//    '#required' => TRUE, // Added
//  );



//  Code sample #5
//  $form['name'] = array(
//    '#type' => 'fieldset',
//    '#title' => t('Name'),
//    '#collapsible' => TRUE,
//    '#collapsed' => FALSE,
//  );
//  $form['name']['first'] = array(
//    '#type' => 'textfield',
//    '#title' => t('First name'),
//    '#required' => TRUE,
//    '#default_value' => "First name", // added
//    '#description' => "Please enter your first name.", // added
//    '#size' => 20, // added
//    '#maxlength' => 20, // added
//  );
//  $form['name']['last'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Last name'),
//    '#required' => TRUE,
//  );


 $form['name'] = array(
    '#type' => 'fieldset',
    '#title' => t('Name'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['name']['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#required' => TRUE,
    '#default_value' => "Tran Hieu",
    '#description' => "Please enter your first name.",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['name']['last'] = array(
    '#type' => 'textfield',
    '#default_value'=>'Dao',
    '#title' => t('Last name'),
    '#required' => TRUE,
  );
  // New form field added to permit entry of year of birth.
  // The data entered into this field will be validated with
  // the default validation function.
  $form['year_of_birth'] = array(
    '#type' => 'textfield',
    '#title' => "Year of birth",
    '#description' => 'Format is "YYYY"',
    '#required' => TRUE,
      '#default_value' => (isset($form_state['values']['year_of_birth'])) ? $form_state['values']['year_of_birth'] : 'Year of Birth',  // replacement
  );

  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
  $form['clear'] = array(
    '#type' => 'submit',
    '#value' => 'Reset form',
    '#validate' => array('myform_my_form_clear'),
  );
    return $form;
}

// This adds a handler/function to validate the data entered into the
// "year of birth" field to make sure it's between the values of 1900
// and 2000. If not, it displays an error. The value report is // $form_state['values'] (see http&#58;//drupal.org/node/144132#form-state).
//
// Notice the name of the function. It is simply the name of the form
// followed by '_validate'. This is the default validation function.
function myform_my_form_validate($form, &$form_state) {
  $year_of_birth = $form_state['values']['year_of_birth'];

  $last_name = $form_state['values']['last'];

  if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
    form_set_error('year_of_birth', 'Enter a year between 1900 and 2000.');
  } else if ($last_name == 'Dao') {
      form_set_error('last', 'Ban khong duoc nhap ten Dao');
  }
}
function myform_my_form_clear($form, &$form_state) {
    $form_state['values']['last'] = '';
    $form_state['rebuild'] = TRUE;
}
function myform_my_form_submit($form, &$form_state) {
    drupal_set_message(t('The form has been submitted.'));

}